### PR TITLE
Update BasketService.php

### PR DESCRIPTION
**Pull request by teiling88**
Remove usage of deprecated function:

image

### CODE REVIEW

**Comment by boxblinkracer** [comment]
oh thanks @teiling88 
that helps a lot
we'll check it out

**Comment by boxblinkracer** [comment]
hey @teiling88 ? wanted to merge this soon (or double check)
not necessary anymore?

**Comment by teiling88** [comment]
It ist still deprecated :-)

**Comment by teiling88** [comment]
Oh sorry - I deleted the repo - I didn't know there was a pr open - sorry.

**Pull request closed without merging**
